const main = () => {
    
}


main().then(dt => process.exit(0)).catch(err => {
    console.log(error);
    process.exit(1)
})